# This is a basic workflow to help you get started with Actions
# TODO: split workflows as described here: https://docs.github.com/en/actions/using-workflows/about-workflows#creating-dependent-jobs

name: Create PDF

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: LaTeX compilation full pdf
        # You may pin to the exact commit or the version.
        # uses: dante-ev/latex-action@49cf7cb5f79e7b2006dbdffea85e02bec0b6244b
        uses: dante-ev/latex-action@2021-A
        with:
          # The root LaTeX file to be compiled
          root_file: cards.tex
          # The working directory for the latex compiler to be invoked
          working_directory: .
          # LaTeX engine to be used
          #compiler: # optional, default is latexmk
          # Extra arguments to be passed to the latex compiler
          #args: # optional, default is -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
          # Install extra packages by apt-get
          #extra_system_packages: # optional

      # TODO: move to requirements.txt
      - name: Install python dependencies
        run: pip install -r requirements.txt
        
      - name: Run split script
        run: python3 split.py

      - name: LaTeX compilation
        # You may pin to the exact commit or the version.
        # uses: dante-ev/latex-action@49cf7cb5f79e7b2006dbdffea85e02bec0b6244b
        uses: dante-ev/latex-action@2021-A
        with:
          # The root LaTeX file to be compiled
          root_file: ""
          # The working directory for the latex compiler to be invoked
          working_directory: split
          # LaTeX engine to be used
          #compiler: # optional, default is latexmk
          # Extra arguments to be passed to the latex compiler
          #args: # optional, default is -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
          # Install extra packages by apt-get
          #extra_system_packages: # optional

        # copy those to a separate directory to archive them
      - name: Copy split pdfs
        run: cp split/*.pdf single/

      # TODO: rename pdf files to german names
      - name: Archive split pdfs
        uses: actions/upload-artifact@v3
        with:
          name: single-pdfs
          path: single/
          
      - name: Archive full pdf
        uses: actions/upload-artifact@v3
        with:
          name: full-pdf
          path: cards.pdf


      - name: Create multipage tex file 2x2
        run: python multi.py --single_pdfs single/ --full_pdf cards.pdf --nup_factor 2 --fold_edge short --output_tex cards_2x2.tex

      - name: Create multipage tex file 3x3
        run: python multi.py --single_pdfs single/ --full_pdf cards.pdf --nup_factor 3 --fold_edge short --output_tex cards_3x3.tex

      - name: Create multipage tex file 4x4
        run: python multi.py --single_pdfs single/ --full_pdf cards.pdf --nup_factor 4 --fold_edge short --output_tex cards_4x4.tex

      - name: Debug output
        run: ls -la single
        
      - name: Debug output
        run: ls -la split
      
      - name: Debug output
        run: cat cards_2x2.tex

      - name: Compile multipage 2x2
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: cards_2x2.tex
          working_directory: .
          #compiler: # optional, default is latexmk
          #args: # optional, default is -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
          #extra_system_packages: # optional

      - name: Archive multipage pdf
        uses: actions/upload-artifact@v3
        with:
          name: cards-2x2-pdf
          path: .build/cards_2x2.pdf

      - name: Compile multipage 3x3
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: cards_3x3.tex
          working_directory: .
          #compiler: # optional, default is latexmk
          #args: # optional, default is -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
          #extra_system_packages: # optional

      - name: Archive multipage pdf
        uses: actions/upload-artifact@v3
        with:
          name: cards-3x3-pdf
          path: .build/cards_3x3.pdf

      - name: Compile multipage 4x4
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: cards_4x4.tex
          working_directory: .
          #compiler: # optional, default is latexmk
          #args: # optional, default is -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
          #extra_system_packages: # optional

      - name: Archive multipage pdf
        uses: actions/upload-artifact@v3
        with:
          name: cards-4x4-pdf
          path: .build/cards_4x4.pdf
